<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Launcher</AssemblyName>
    <RootNamespace>BackToTheFutureLauncher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>launcher.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="episode-preferences\Episode 1\prefs.prop"
                      LogicalName="EpisodePreferences.Episode1.prefs.prop" />
    <EmbeddedResource Include="episode-preferences\Back to the Future 2\prefs.prop"
                      LogicalName="EpisodePreferences.Episode2.prefs.prop" />
    <EmbeddedResource Include="episode-preferences\Back to the Future 3\prefs.prop"
                      LogicalName="EpisodePreferences.Episode3.prefs.prop" />
    <EmbeddedResource Include="episode-preferences\Back to the Future 4\prefs.prop"
                      LogicalName="EpisodePreferences.Episode4.prefs.prop" />
    <EmbeddedResource Include="episode-preferences\Back to the Future 5\prefs.prop"
                      LogicalName="EpisodePreferences.Episode5.prefs.prop" />
    <None Update="launcher.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <Content Include="launcher.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>
</Project>
